# Generated by Django 4.2.17 on 2024-12-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MRIImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploads/mri_images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("prediction", models.CharField(blank=True, max_length=50, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
