# Generated by Django 4.2.17 on 2025-06-02 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("detection", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mriimage",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mri_images",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
